# Generated by Django 5.2.10 on 2026-01-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='finance.budgetallocation'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.financialyear'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('project', 'financial_year')},
        ),
    ]
